# Generated by Django 3.1 on 2020-08-12 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipgserver',
            name='server',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cloud.server'),
        ),
        migrations.AlterField(
            model_name='webcmserver',
            name='server',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cloud.server'),
        ),
    ]
