# Generated by Django 3.1 on 2020-08-14 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0002_auto_20200812_2116'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Last Updated'),
        ),
    ]
