# Generated by Django 3.1 on 2020-08-14 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0003_server_last_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='expiration_processed',
            field=models.BooleanField(default=False, verbose_name='Expiration Processed'),
        ),
    ]
