# Generated by Django 3.1 on 2020-08-15 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0004_subscription_expiration_processed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='state',
            field=models.CharField(default='Initializing', max_length=255, null=True),
        ),
    ]
