# Generated by Django 3.1 on 2020-08-18 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0005_auto_20200815_1826'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='server',
            name='last_updated',
        ),
        migrations.AddField(
            model_name='server',
            name='oncommand',
            field=models.BooleanField(default=False, verbose_name='On Command'),
        ),
    ]
