# Generated by Django 3.1 on 2020-11-23 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0007_server_static_ip'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsedIp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP Address')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'used ip',
                'verbose_name_plural': 'used ips',
            },
        ),
    ]
