# Generated by Django 3.1 on 2020-11-23 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0008_usedip'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cluster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(protocol='IPv4', verbose_name='Ip Address')),
                ('token', models.TextField(verbose_name='Token')),
                ('static_pool', models.CharField(max_length=50, verbose_name='Static Pool')),
                ('active', models.BooleanField(verbose_name='Active')),
            ],
            options={
                'verbose_name': 'cluster',
                'verbose_name_plural': 'clusters',
            },
        ),
    ]
