# Generated by Django 3.1 on 2020-11-26 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0009_cluster'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cluster',
            name='ip_address',
        ),
        migrations.AddField(
            model_name='cluster',
            name='host',
            field=models.CharField(default='https://192.168.28.241:6443', max_length=300, verbose_name='Host'),
            preserve_default=False,
        ),
    ]
