# Generated by Django 3.1 on 2020-11-29 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0010_auto_20201126_2154'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipgserver',
            name='idstr',
            field=models.CharField(default='xxx', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='webcmserver',
            name='idstr',
            field=models.CharField(default='xxx', max_length=255),
            preserve_default=False,
        ),
    ]
