# Generated by Django 3.1 on 2020-11-30 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0011_auto_20201129_1118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ipgserver',
            name='idstr',
        ),
        migrations.RemoveField(
            model_name='webcmserver',
            name='idstr',
        ),
        migrations.AddField(
            model_name='subscription',
            name='idstr',
            field=models.CharField(default='0', max_length=255),
        ),
    ]
