# Generated by Django 3.1 on 2020-11-30 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0012_auto_20201130_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='subscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servers', to='cloud.subscription'),
        ),
    ]
