# Generated by Django 3.1 on 2020-12-01 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0013_auto_20201130_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipgserver',
            name='server',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ipgserver', to='cloud.server'),
        ),
        migrations.AlterField(
            model_name='webcmserver',
            name='server',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='webcmserver', to='cloud.server'),
        ),
    ]
