# Generated by Django 3.1 on 2020-12-09 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0014_auto_20201201_2135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='server',
            name='oncommand',
        ),
        migrations.AddField(
            model_name='server',
            name='operation',
            field=models.CharField(choices=[('command', 'command'), ('none', 'none')], default='none', max_length=50, verbose_name='Current Operation'),
        ),
    ]
