# Generated by Django 3.1 on 2021-01-09 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0015_auto_20201209_2024'),
    ]

    operations = [
        migrations.AddField(
            model_name='usedip',
            name='used',
            field=models.BooleanField(default=False, verbose_name='Used'),
        ),
    ]
